REFERENCE/kimai-main/src/Entity/Activity.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Doctrine\Behavior\CreatedAt;
use App\Doctrine\Behavior\CreatedTrait;
use App\Export\Annotation as Exporter;
use App\Repository\ActivityRepository;
use App\Validator\Constraints as Constraints;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use JMS\Serializer\Annotation as Serializer;
use OpenApi\Attributes as OA;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'kimai2_activities')]
#[ORM\Index(columns: ['visible', 'project_id'])]
#[ORM\Index(columns: ['visible', 'project_id', 'name'])]
#[ORM\Index(columns: ['visible', 'name'])]
#[ORM\Entity(repositoryClass: ActivityRepository::class)]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
#[Serializer\ExclusionPolicy('all')]
#[Serializer\VirtualProperty('ProjectName', exp: 'object.getProject() === null ? null : object.getProject().getName()', options: [new Serializer\SerializedName('parentTitle'), new Serializer\Type(name: 'string'), new Serializer\Groups(['Activity'])])]
#[Serializer\VirtualProperty('ProjectAsId', exp: 'object.getProject() === null ? null : object.getProject().getId()', options: [new Serializer\SerializedName('project'), new Serializer\Type(name: 'integer'), new Serializer\Groups(['Activity', 'Team', 'Not_Expanded'])])]
#[Exporter\Order(['id', 'name', 'project', 'budget', 'timeBudget', 'budgetType', 'color', 'visible', 'comment', 'billable', 'number'])]
#[Exporter\Expose(name: 'project', label: 'project', exp: 'object.getProject() === null ? null : object.getProject().getName()')]
#[Constraints\Activity]
class Activity implements EntityWithMetaFields, EntityWithBudget, CreatedAt
{
    use BudgetTrait;
    use ColorTrait;
    use CreatedTrait;

    /**
     * Unique activity ID
     */
    #[ORM\Column(name: 'id', type: Types::INTEGER)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'id', type: 'integer')]
    private ?int $id = null;
    #[ORM\ManyToOne(targetEntity: Project::class)]
    #[ORM\JoinColumn(nullable: true, onDelete: 'CASCADE')]
    #[Serializer\Expose]
    #[Serializer\Groups(['Subresource', 'Expanded'])]
    #[OA\Property(ref: '#/components/schemas/ProjectExpanded')]
    private ?Project $project = null;
    /**
     * Name of this activity
     */
    #[ORM\Column(name: 'name', type: Types::STRING, length: 150, nullable: false)]
    #[Assert\NotBlank]
    #[Assert\Length(min: 2, max: 150)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'name')]
    private ?string $name = null;
    /**
     * Description of this activity
     */
    #[ORM\Column(name: 'comment', type: Types::TEXT, nullable: true)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'comment')]
    private ?string $comment = null;
    /**
     * Whether this activity is visible and can be selected
     */
    #[ORM\Column(name: 'visible', type: Types::BOOLEAN, nullable: false, options: ['default' => true])]
    #[Assert\NotNull]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'visible', type: 'boolean')]
    private bool $visible = true;
    #[ORM\Column(name: 'billable', type: Types::BOOLEAN, nullable: false, options: ['default' => true])]
    #[Assert\NotNull]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'billable', type: 'boolean')]
    private bool $billable = true;
    /**
     * Meta fields registered with the activity
     *
     * @var Collection<ActivityMeta>
     */
    #[ORM\OneToMany(mappedBy: 'activity', targetEntity: ActivityMeta::class, cascade: ['persist'])]
    #[Serializer\Expose]
    #[Serializer\Groups(['Activity'])]
    #[Serializer\Type(name: 'array<App\Entity\ActivityMeta>')]
    #[Serializer\SerializedName('metaFields')]
    #[Serializer\Accessor(getter: 'getVisibleMetaFields')]
    private Collection $meta;
    /**
     * Teams with access to the activity
     *
     * @var Collection<Team>
     */
    #[ORM\JoinTable(name: 'kimai2_activities_teams')]
    #[ORM\JoinColumn(name: 'activity_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\InverseJoinColumn(name: 'team_id', referencedColumnName: 'id', onDelete: 'CASCADE')]
    #[ORM\ManyToMany(targetEntity: Team::class, inversedBy: 'activities', cascade: ['persist'])]
    #[Serializer\Expose]
    #[Serializer\Groups(['Activity'])]
    #[OA\Property(type: 'array', items: new OA\Items(ref: '#/components/schemas/Team'))]
    private Collection $teams;
    #[ORM\Column(name: 'invoice_text', type: Types::TEXT, nullable: true)]
    private ?string $invoiceText = null;
    #[ORM\Column(name: 'number', type: Types::STRING, length: 10, nullable: true)]
    #[Assert\Length(max: 10)]
    #[Serializer\Expose]
    #[Serializer\Groups(['Default'])]
    #[Exporter\Expose(label: 'activity_number')]
    private ?string $number = null;

    public function __construct()
    {
        $this->meta = new ArrayCollection();
        $this->teams = new ArrayCollection();
        $this->setCreatedAt(new \DateTimeImmutable('now', new \DateTimeZone('UTC')));
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isNew(): bool
    {
        return $this->id === null;
    }

    public function getProject(): ?Project
    {
        return $this->project;
    }

    public function setProject(?Project $project): Activity
    {
        $this->project = $project;

        return $this;
    }

    public function setName(string $name): Activity
    {
        $this->name = $name;

        return $this;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setComment(?string $comment): Activity
    {
        $this->comment = $comment;

        return $this;
    }

    public function getComment(): ?string
    {
        return $this->comment;
    }

    public function setVisible(bool $visible): Activity
    {
        $this->visible = $visible;

        return $this;
    }

    public function isGlobal(): bool
    {
        return $this->project === null;
    }

    public function isVisible(): bool
    {
        return $this->visible;
    }

    public function setBillable(bool $billable): void
    {
        $this->billable = $billable;
    }

    public function isBillable(): bool
    {
        return $this->billable;
    }

    /**
     * @return Collection|MetaTableTypeInterface[]
     */
    public function getMetaFields(): Collection
    {
        return $this->meta;
    }

    /**
     * @return MetaTableTypeInterface[]
     */
    public function getVisibleMetaFields(): array
    {
        $all = [];
        foreach ($this->meta as $meta) {
            if ($meta->isVisible()) {
                $all[] = $meta;
            }
        }

        return $all;
    }

    public function getMetaField(string $name): ?MetaTableTypeInterface
    {
        foreach ($this->meta as $field) {
            if (strtolower($field->getName()) === strtolower($name)) {
                return $field;
            }
        }

        return null;
    }

    public function setMetaField(MetaTableTypeInterface $meta): EntityWithMetaFields
    {
        if (null === ($current = $this->getMetaField($meta->getName()))) {
            $meta->setEntity($this);
            $this->meta->add($meta);

            return $this;
        }

        $current->merge($meta);

        return $this;
    }

    public function addTeam(Team $team): void
    {
        if ($this->teams->contains($team)) {
            return;
        }

        $this->teams->add($team);
        $team->addActivity($this);
    }

    public function removeTeam(Team $team): void
    {
        if (!$this->teams->contains($team)) {
            return;
        }
        $this->teams->removeElement($team);
        $team->removeActivity($this);
    }

    /**
     * @return Collection<Team>
     */
    public function getTeams(): Collection
    {
        return $this->teams;
    }

    public function getInvoiceText(): ?string
    {
        return $this->invoiceText;
    }

    public function setInvoiceText(?string $invoiceText): void
    {
        $this->invoiceText = $invoiceText;
    }

    public function setNumber(?string $number): void
    {
        $this->number = $number;
    }

    public function getNumber(): ?string
    {
        return $this->number;
    }

    public function __toString(): string
    {
        return $this->getName();
    }

    public function __clone()
    {
        if ($this->id !== null) {
            $this->id = null;
        }

        $this->setCreatedAt(new \DateTimeImmutable('now', new \DateTimeZone('UTC')));

        $currentTeams = $this->teams;
        $this->teams = new ArrayCollection();
        /** @var Team $team */
        foreach ($currentTeams as $team) {
            $this->addTeam($team);
        }

        $this->number = null;
        $currentMeta = $this->meta;
        $this->meta = new ArrayCollection();
        /** @var ActivityMeta $meta */
        foreach ($currentMeta as $meta) {
            $newMeta = clone $meta;
            $newMeta->setEntity($this);
            $this->setMetaField($newMeta);
        }
    }
}

REFERENCE/kimai-main/src/Entity/Role.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Entity;

use App\Repository\RoleRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Table(name: 'kimai2_roles')]
#[ORM\UniqueConstraint(name: 'roles_name', columns: ['name'])]
#[ORM\Entity(repositoryClass: RoleRepository::class)]
#[ORM\ChangeTrackingPolicy('DEFERRED_EXPLICIT')]
#[UniqueEntity('name')]
class Role
{
    #[ORM\Column(name: 'id', type: Types::INTEGER)]
    #[ORM\Id]
    #[ORM\GeneratedValue(strategy: 'IDENTITY')]
    private ?int $id = null;
    #[ORM\Column(name: 'name', type: Types::STRING, length: 50, nullable: false)]
    #[Assert\NotNull]
    #[Assert\NotBlank]
    #[Assert\Length(min: 5, max: 50)]
    private ?string $name = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): Role
    {
        $this->name = strtoupper($name);

        return $this;
    }

    public function isUser(): bool
    {
        return $this->name === User::ROLE_USER;
    }
}

REFERENCE/kimai-main/src/Form/Helper/ActivityHelper.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form\Helper;

use App\Configuration\SystemConfiguration;
use App\Entity\Activity;

final class ActivityHelper
{
    public const PATTERN_NUMBER = '{number}';
    public const PATTERN_NAME = '{name}';
    public const PATTERN_COMMENT = '{comment}';
    public const PATTERN_SPACER = '{spacer}';
    public const SPACER = ' - ';

    private ?string $pattern = null;

    public function __construct(private readonly SystemConfiguration $configuration)
    {
    }

    public function getChoicePattern(): string
    {
        if ($this->pattern === null) {
            $this->pattern = $this->configuration->find('activity.choice_pattern');

            if ($this->pattern === null || stripos($this->pattern, '{') === false || stripos($this->pattern, '}') === false) {
                $this->pattern = self::PATTERN_NAME;
            }

            $this->pattern = str_replace(self::PATTERN_SPACER, self::SPACER, $this->pattern);
        }

        return $this->pattern;
    }

    public function getChoiceLabel(Activity $activity): string
    {
        $name = $this->getChoicePattern();
        $name = str_replace(self::PATTERN_NAME, $activity->getName() ?? '', $name);
        $name = str_replace(self::PATTERN_NUMBER, $activity->getNumber() ?? '', $name);
        $name = str_replace(self::PATTERN_COMMENT, $activity->getComment() ?? '', $name);

        while (str_starts_with($name, self::SPACER)) {
            $name = substr($name, \strlen(self::SPACER));
        }

        while (str_ends_with($name, self::SPACER)) {
            $name = substr($name, 0, -\strlen(self::SPACER));
        }

        if ($name === '' || $name === self::SPACER) {
            $name = $activity->getName() ?? '';
        }

        return substr($name, 0, 110);
    }
}

REFERENCE/kimai-main/src/Form/Type/ActivityType.php
<?php

/*
 * This file is part of the Kimai time-tracking app.
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace App\Form\Type;

use App\Entity\Activity;
use App\Form\Helper\ActivityHelper;
use App\Form\Helper\ProjectHelper;
use App\Repository\ActivityRepository;
use App\Repository\Query\ActivityFormTypeQuery;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\Options;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Custom form field type to select an activity.
 */
final class ActivityType extends AbstractType
{
    public function __construct(private readonly ActivityHelper $activityHelper, private readonly ProjectHelper $projectHelper)
    {
    }

    public function getChoiceLabel(Activity $activity): string
    {
        return $this->activityHelper->getChoiceLabel($activity);
    }

    public function groupBy(Activity $activity, $key, $index): string
    {
        if (null === $activity->getProject()) {
            // this creates a optgroup with an empty title. previously this was null, which resulted in options without optgroup
            // and those are ordered by Tomselect at the top - so globals always came first, see #4674
            return '';
        }

        return $this->projectHelper->getChoiceLabel($activity->getProject());
    }

    /**
     * @param Activity $activity
     * @param string $key
     * @param mixed $value
     * @return array<string, string|int|null>
     */
    public function getChoiceAttributes(Activity $activity, $key, $value): array
    {
        if (null !== ($project = $activity->getProject())) {
            return ['data-project' => $project->getId(), 'data-currency' => $project->getCustomer()?->getCurrency()];
        }

        return [];
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            // documentation is for NelmioApiDocBundle
            'documentation' => [
                'type' => 'integer',
                'description' => 'Activity ID',
            ],
            'label' => 'activity',
            'class' => Activity::class,
            'choice_label' => [$this, 'getChoiceLabel'],
            'choice_attr' => [$this, 'getChoiceAttributes'],
            'group_by' => [$this, 'groupBy'],
            'query_builder_for_user' => true,
            // @var Project|Project[]|int|int[]|null
            'projects' => null,
            // @var Activity|Activity[]|int|int[]|null
            'activities' => null,
            // @var Activity|null
            'ignore_activity' => null,
            'allow_create' => false,
        ]);

        $resolver->setDefault('api_data', function (Options $options) {
            if (false !== $options['allow_create']) {
                return ['create' => 'post_activity'];
            }

            return [];
        });

        $resolver->setDefault('query_builder', function (Options $options) {
            return function (ActivityRepository $repo) use ($options) {
                $query = new ActivityFormTypeQuery($options['activities'], $options['projects']);

                if (true === $options['query_builder_for_user']) {
                    $query->setUser($options['user']);
                }

                if (null !== $options['ignore_activity']) {
                    $query->setActivityToIgnore($options['ignore_activity']);
                }

                return $repo->getQueryBuilderForFormType($query);
            };
        });
    }

    public function buildView(FormView $view, FormInterface $form, array $options): void
    {
        $view->vars['attr'] = array_merge($view->vars['attr'], [
            'data-option-pattern' => $this->activityHelper->getChoicePattern(),
        ]);
    }

    public function getParent(): string
    {
        return EntityType::class;
    }
}

REFERENCE/kimai-main/templates/activity/actions.html.twig
{% macro activity(activity, view, isTable) %}
    {% import "macros/widgets.html.twig" as widgets %}
    {% set event = actions(app.user, 'activity', view, {'activity': activity}) %}
    {% if view == 'index' or view == 'custom' or isTable is not null %}
        {{ widgets.table_actions(event.actions) }}
    {% else %}
        {{ widgets.page_actions(event.actions) }}
    {% endif %}
{% endmacro %}

REFERENCE/kimai-main/templates/activity/delete.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {% set params = {
        '%records%': stats.counter,
        '%duration%': stats.duration|duration
    } %}
    {{ include(kimai_context.modalRequest ? 'default/_form_delete_modal.html.twig' : 'default/_form_delete.html.twig', {
        'message': ("delete_warning.short_stats"|trans(params) ~ "admin_entity.delete_confirm"|trans),
        'form': form,
        'delete_item_name': activity.name,
        'used': (stats.counter > 0),
        'back': path('admin_activity')
    }) }}
{% endblock %}

REFERENCE/kimai-main/templates/activity/details.html.twig
{% extends 'base.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}

{% block main %}
    {% set can_edit = is_granted('edit', activity) %}
    {% set currency = null %}
    {% if activity.project is not null %}
        {% set currency = activity.project.customer.currency %}
    {% endif %}

    {% embed '@theme/embeds/card.html.twig' %}
        {% import "macros/widgets.html.twig" as widgets %}
        {% import "customer/actions.html.twig" as customerActions %}
        {% import "project/actions.html.twig" as projectActions %}
        {% block box_attributes %}id="activity_details_box"{% endblock %}
        {% block box_title %}
            {{ widgets.label_dot(activity.name, activity.color) }}
        {% endblock %}
        {% block box_tools %}
            {% if can_edit %}
                {{ widgets.card_tool_button('edit', {'class': 'modal-ajax-form open-edit', 'title': 'edit', 'url': path('admin_activity_edit', {'id': activity.id})}) }}
            {% endif %}
        {% endblock %}
        {% block box_body_class %}p-0{% endblock %}
        {% block box_body %}
            {% if activity.comment is not empty %}
                <div class="comment p-3">
                    {{ activity.comment|comment2html(true) }}
                </div>
            {% endif %}
            <table class="table table-hover dataTable">
                {% if not activity.visible %}
                    <tr class="{{ widgets.class_activity_row(activity, now) }}">
                        <th>{{ 'visible'|trans }}</th>
                        <td colspan="3">
                            {{ widgets.label_boolean(activity.visible) }}
                        </td>
                    </tr>
                {% endif %}
                {% if not activity.billable %}
                    <tr>
                        <th>{{ 'billable'|trans }}</th>
                        <td colspan="3">
                            {{ widgets.label_boolean(activity.billable) }}
                        </td>
                    </tr>
                {% endif %}
                {% if not activity.global %}
                    <tr {{ widgets.customer_row_attr(activity.project.customer, now) }}>
                        <th>{{ 'customer'|trans }}</th>
                        <td>
                            {{ widgets.label_customer(activity.project.customer) }}
                        </td>
                        <td class="w-min">
                            {{ widgets.badge_team_access(activity.project.customer.teams) }}
                        </td>
                        <td class="actions">
                            {{ customerActions.customer(activity.project.customer, 'custom') }}
                        </td>
                    </tr>
                    <tr {{ widgets.project_row_attr(activity.project, now) }}>
                        <th>{{ 'project'|trans }}</th>
                        <td>
                            {{ widgets.label_project(activity.project) }}
                        </td>
                        <td class="w-min">
                            {{ widgets.badge_team_access(activity.project.teams) }}
                        </td>
                        <td class="actions">
                            {{ projectActions.project(activity.project, 'custom') }}
                        </td>
                    </tr>
                {% endif %}
                {% if activity.number is not empty %}
                    <tr>
                        <th>{{ 'activity_number'|trans }}</th>
                        <td colspan="3">
                            {{ activity.number }}
                        </td>
                    </tr>
                {% endif %}
                {% for metaField in activity.visibleMetaFields|filter(field => field.defined)|sort((a, b) => a.order <=> b.order) %}
                    <tr>
                        <th>{{ metaField.label|trans }}</th>
                        <td colspan="3">{{ widgets.form_type_value(metaField.type, metaField.value, activity) }}</td>
                    </tr>
                {% endfor %}
            </table>
        {% endblock %}
    {% endembed %}

    {% if can_edit %}
        {{ include('embeds/rates-table.html.twig', {'id': 'activity_rates_box', 'entity': activity, 'create_url': path('admin_activity_rate_add', {'id': activity.id}), 'delete_route': 'delete_activity_rate', 'currency': currency, 'edit_route': 'admin_activity_rate_edit'}) }}
    {% endif %}

    {% if stats is not null %}
        {% set currency = kimai_config.customerDefaultCurrency %}
        {% if activity.project is not null %}
            {% set currency = activity.project.customer.currency %}
        {% endif %}
        {{ include('embeds/budgets.html.twig', {'entity': activity, 'stats': stats, 'currency': currency}) }}
    {% endif %}

    {% for controller in boxes %}
        {{ render(controller(controller, {'activity': activity, 'page': 1})) }}
    {% endfor %}

    {% if teams is not null %}
        {% set options = {'teams': teams, 'team': team} %}
        {% if is_granted('permissions', activity) %}
            {% set options = options|merge({'route_create': path('activity_team_create', {'id': activity.id}), 'route_edit': path('admin_activity_permissions', {'id': activity.id})}) %}
        {% endif %}
        {% if activity.project is not null and (activity.project.teams|length > 0 or activity.project.customer.teams|length > 0) %}
            {% set options = options|merge({'empty_message': 'team.activity_visibility_inherited'}) %}
        {% endif %}
        {{ include('embeds/teams.html.twig', options) }}
    {% endif %}

{% endblock %}

{% block javascripts %}
    {{ parent() }}
    <script type="text/javascript">
        document.addEventListener('kimai.initialized', function() {
            KimaiReloadPageWidget.create('kimai.activityUpdate kimai.teamUpdate kimai.activityTeamUpdate kimai.projectTeamUpdate kimai.customerTeamUpdate kimai.customerUpdate kimai.projectUpdate kimai.rateUpdate');
        });
    </script>
{% endblock %}

REFERENCE/kimai-main/templates/activity/edit.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {% set formEditTemplate = kimai_context.modalRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig' %}
    {% set formOptions = {
        'title': (activity.id is null ? 'create-activity'|trans : 'edit'|trans),
        'form': form,
        'back': path('admin_activity')
    } %}
    {% embed formEditTemplate with formOptions %}
        {% block form_body %}
            <div class="row">
                <div class="col-md-9">
                    {{ form_row(form.name) }}
                </div>
                <div class="col-md-3">
                    {{ form_row(form.color) }}
                </div>
            </div>
            {{ form_row(form.comment) }}
            {% if form.customer is defined %}
                {{ form_row(form.customer) }}
            {% endif %}
            {% if form.project is defined %}
                {{ form_row(form.project) }}
            {% endif %}
            {{ form_row(form.number) }}
            {% if form.budgetType is defined %}
                <div class="row">
                    {% if form.budget is defined %}
                        <div class="col-md-4">
                            {{ form_row(form.budget) }}
                        </div>
                    {% endif %}
                    {% if form.timeBudget is defined %}
                        <div class="col-md-4">
                            {{ form_row(form.timeBudget) }}
                        </div>
                    {% endif %}
                    <div class="col-md-4">
                        {{ form_row(form.budgetType) }}
                    </div>
                </div>
            {% endif %}
            {% if form.teams is defined %}
                <div class="row">
                    <div class="col-12">
                        {{ form_row(form.teams) }}
                    </div>
                </div>
            {% endif %}
            <div class="row">
                <div class="col-md-6">
                    {{ form_row(form.visible) }}
                </div>
                <div class="col-md-6">
                    {{ form_row(form.billable) }}
                </div>
            </div>
            {% if form.metaFields is defined and form.metaFields is not empty %}
                {{ form_row(form.metaFields) }}
            {% endif %}
            {% embed '@theme/embeds/collapsible.html.twig' with {id: 'activity_invoice_settings'} %}
                {% import "macros/widgets.html.twig" as widgets %}
                {% block title %}{{ 'invoices'|trans }}{% endblock %}
                {% block body %}
                    {% if form.invoiceText is defined %}
                        {{ form_row(form.invoiceText) }}
                    {% endif %}
                {% endblock %}
            {% endembed %}
            {{ form_rest(form) }}
        {% endblock %}
    {% endembed %}
{% endblock %}

REFERENCE/kimai-main/templates/activity/index.html.twig
{% extends 'datatable.html.twig' %}
{% import "macros/widgets.html.twig" as widgets %}
{% import "activity/actions.html.twig" as actions %}

{% block datatable_row_attr %} {{ widgets.activity_row_attr(entry, now) }}{% endblock %}

{% block datatable_column_value %}
    {% if column == 'name' %}
        {{ widgets.label_name(entry.name, entry.color|colorize(entry.name)) }}
    {% elseif column == 'project' %}
        {# only none-global activities have a project and customer assigned #}
        {% if entry.project %}
            {{ widgets.label_project(entry.project) }}
            {% if entry.project.customer %}
                <br>
                <small>
                    {{ widgets.label_customer(entry.project.customer) }}
                </small>
            {% endif %}
        {% endif %}
    {% elseif column == 'comment' %}
        {{ entry.comment|comment1line }}
    {% elseif column == 'number' %}
        {{ entry.number }}
    {% elseif column == 'budget' %}
        {% if entry.hasBudget() and is_granted('budget', entry) %}
            {{ entry.budget|money((entry.project is null ? defaultCurrency : entry.project.customer.currency)) }}
        {% else %}
            &ndash;
        {% endif %}
    {% elseif column == 'timeBudget' %}
        {% if entry.hasTimeBudget() and is_granted('time', entry) %}
            {{ entry.timeBudget|duration }}
        {% else %}
            &ndash;
        {% endif %}
    {% elseif column == 'billable' %}
        {{ widgets.label_boolean(entry.billable) }}
    {% elseif column == 'team' %}
        {{ widgets.badge_team_access(entry.teams) }}
    {% elseif column == 'visible' %}
        {{ widgets.label_visible(entry.visible) }}
    {% elseif column == 'actions' %}
        {{ actions.activity(entry, 'index') }}
    {% elseif column starts with 'mf_' %}
        {{ widgets.meta_field_value(entry, data) }}
    {% endif %}
{% endblock %}

REFERENCE/kimai-main/templates/activity/permissions.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {{ include(kimai_context.modalRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': ('permissions'|trans) ~ ': ' ~ activity.name,
        'form': form,
        'back': path('activity_details', {'id': activity.id})
    }) }}
{% endblock %}

REFERENCE/kimai-main/templates/activity/rates.html.twig
{% extends kimai_context.modalRequest ? 'form.html.twig' : 'base.html.twig' %}

{% block main %}
    {{ include(kimai_context.modalRequest ? 'default/_form_modal.html.twig' : 'default/_form.html.twig', {
        'title': activity.name,
        'form': form,
        'back': path('admin_activity')
    }) }}
{% endblock %}